import Head from "next/head";
import Join from "../src/components/Join";

export default function JoinUs() {
  return (
    <>
      <Head>
        <title>Join Us | Georgia Tech XR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Join />
    </>
  );
}
