import Head from "next/head";
import ProjectsContributors from "../src/components/ProjectsContributors";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Projects | Georgia Tech XR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProjectsContributors />
    </>
  );
}
